# Create a program that will play the "cows and bulls" game with the user.
# The game works like this:

#  - Randomly generate a 4-digit number.
#  - Ask the user to guess a 4-digit number.
#  - For every digit that the user guessed correctly in the correct place,
#     they have a "cow".
#  - For every digit the user guessed correctly, but not in the correct
#     place is a "bull."
#  - Every time the user makes a guess, tell them how many "cows" and
#     "bulls" they have.
#  - Once the user guesses the correct number, the game is over.
#  - Keep track of the number of guesses the user makes throughout the game
#     and tell the user at the end.

# An example run could look like this: (the number generated by the computer is 1038)
'''
  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ... <user keeps guessing> ...
  >>> 1083
  2 cow, 2 bulls
  >>> 1038
  Congratulations! That is correct!
  It took 14 guesses to get the correct number.
'''
